title: Arturas Valiauga
email: email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  
baseurl: "/index.md" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme:
plugins:
  - jekyll-feed

include: 
    ['_pages']
    
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
